name: setup
description: Setup gradle
runs:
  using: composite
  steps:
    - uses: ./.github/actions/setup/java
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: 8.11