name: test

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - dev
      - main
  push:
    branches:
      - dev
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build, Test, and Analyze
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          repository: ${{ github.event.repository.full_name }}
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Setup Gradle
        uses: ./.github/actions/setup/gradle

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: |
            # Handle windows and unix paths
            ~\.sonar/cache
            ~/.sonar/cache
          key: ${{ runner.os }}-sonar-${{ hashFiles('**/sonar-project.properties') }}
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Gradle Windows packages
        if: runner.os == 'Windows'
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.USERPROFILE }}\.gradle\caches
            ${{ env.USERPROFILE }}\.gradle\wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Cache Gradle Unix packages
        if: runner.os != 'Windows'
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Build, Test, and Analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
        run: ./gradlew clean build sonar --stacktrace --scan --no-daemon --debug --max-workers 2
